apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-agent-service
  namespace: platform-vva-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: platform-agent-deployer
  namespace: platform-vva-agent
rules:
  - apiGroups: [""]
    resources: ["services", "pods", "pods/log", "namespaces"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: platform-agent-deployer
  namespace: platform-vva-agent
subjects:
  - kind: ServiceAccount
    name: platform-agent-service
    namespace: platform-vva-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: platform-agent-deployer
